---
builds:
  - env:
    - CGO_ENABLED=0
    goos:
    - windows
    - linux
    - darwin
    goarch:
    - amd64
    - arm64
    main: ./cmd/dyff/main.go
    flags:
    - -trimpath
    ldflags:
    - -s -w -extldflags "-static" -X github.com/homeport/dyff/internal/cmd.version={{.Version}}
    mod_timestamp: '{{ .CommitTimestamp }}'

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  name_template: "{{.ProjectName}} release v{{.Version}}"

changelog:
  skip: false
  sort: ""
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brews:
- tap:
    owner: homeport
    name: homebrew-tap
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
  url_template: "https://github.com/homeport/dyff/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  download_strategy: CurlDownloadStrategy
  commit_author:
    name: GoReleaser Bot
    email: goreleaser@carlosbecker.com
  folder: HomebrewFormula
  homepage: "https://github.com/homeport/dyff"
  description: "δyƒƒ /ˈdʏf/ - A diff tool for YAML files, and sometimes JSON"
  license: "MIT"
  skip_upload: false
  test: |
    system "#{bin}/dyff version"

snapcrafts:
- id: dyff
  publish: true
  summary: "YAML diff tool"
  description: "δyƒƒ /ˈdʏf/ - A diff tool for YAML files, and sometimes JSON"
  grade: stable
  confinement: strict
  license: MIT
  base: bare
  apps:
    dyff:
      plugs: ["home", "network"]
